// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOGnfuvIKFVra743LDPTZ-PZ58hxyuz3o',
    appId: '1:938512089449:web:6f5eaae46d451be924fdf8',
    messagingSenderId: '938512089449',
    projectId: 'fir-tutoriouseingriverpod',
    authDomain: 'fir-tutoriouseingriverpod.firebaseapp.com',
    storageBucket: 'fir-tutoriouseingriverpod.firebasestorage.app',
    measurementId: 'G-Z43Z7YKLSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcmkghBUvIEt49OGvCgNLbLxPPCJyPntY',
    appId: '1:938512089449:android:0683aac046be478924fdf8',
    messagingSenderId: '938512089449',
    projectId: 'fir-tutoriouseingriverpod',
    storageBucket: 'fir-tutoriouseingriverpod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDThWKTMAi3lA52tg2QgAfisHxusFQl3nw',
    appId: '1:938512089449:ios:ad123950773648a724fdf8',
    messagingSenderId: '938512089449',
    projectId: 'fir-tutoriouseingriverpod',
    storageBucket: 'fir-tutoriouseingriverpod.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDThWKTMAi3lA52tg2QgAfisHxusFQl3nw',
    appId: '1:938512089449:ios:ad123950773648a724fdf8',
    messagingSenderId: '938512089449',
    projectId: 'fir-tutoriouseingriverpod',
    storageBucket: 'fir-tutoriouseingriverpod.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOGnfuvIKFVra743LDPTZ-PZ58hxyuz3o',
    appId: '1:938512089449:web:823faa06cffb0dc224fdf8',
    messagingSenderId: '938512089449',
    projectId: 'fir-tutoriouseingriverpod',
    authDomain: 'fir-tutoriouseingriverpod.firebaseapp.com',
    storageBucket: 'fir-tutoriouseingriverpod.firebasestorage.app',
    measurementId: 'G-Q233J5GTL6',
  );
}
